// <auto-generated />
namespace DataMapping.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class osama : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(osama));
        
        string IMigrationMetadata.Id
        {
            get { return "202102121629157_osama"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
