namespace DataMapping.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class addMenuByDateWebNutritionTbl : DbMigration
    {
        public override void Up()
        {
            CreateTable(
                "GL.MenuByDateWebNutrition",
                c => new
                    {
                        LM_ID = c.Int(nullable: false, identity: true),
                        MH_NameAr = c.String(),
                        MH_NameEng = c.String(),
                        FromDate = c.String(),
                        ToDate = c.String(),
                        DateDay = c.DateTime(),
                        Program = c.Single(),
                        ConvertTProgramType = c.Single(),
                        M1ID = c.Int(),
                        M1NameEng = c.String(),
                        M1NameAr = c.String(),
                        M1Calories = c.Single(),
                        MealTime1 = c.Single(),
                        CaloriesPr1 = c.Single(),
                        WeighM1 = c.Single(),
                        ProteinM1 = c.Single(),
                        FatM1 = c.Single(),
                        CarbohydrateM1 = c.Single(),
                        M2ID = c.Int(),
                        M2NameEng = c.String(),
                        M2NameAr = c.String(),
                        M2Calories = c.Single(),
                        MealTime2 = c.Single(),
                        Expr1 = c.Single(),
                        WeighM2 = c.Single(),
                        ProteinM2 = c.Single(),
                        FatM2 = c.Single(),
                        CarbohydrateM2 = c.Single(),
                        M3ID = c.Int(),
                        M3NameEng = c.String(),
                        M3NameAr = c.String(),
                        M3Calories = c.Single(),
                        MealTime3 = c.Single(),
                        Expr2 = c.Single(),
                        WeighM3 = c.Single(),
                        ProteinM3 = c.Single(),
                        FatM3 = c.Single(),
                        CarbohydrateM3 = c.Single(),
                        M4ID = c.Int(),
                        M4NameEng = c.String(),
                        M4NameAr = c.String(),
                        M4Calories = c.Single(),
                        MealTime4 = c.Single(),
                        Expr3 = c.Single(),
                        WeighM4 = c.Single(),
                        ProteinM4 = c.Single(),
                        FatM4 = c.Single(),
                        CarbohydrateM4 = c.Single(),
                        M5ID = c.Int(),
                        M5NameEng = c.String(),
                        M5NameAr = c.String(),
                        M5Calories = c.Single(),
                        MealTime5 = c.Single(),
                        Expr4 = c.Single(),
                        WeighM5 = c.Single(),
                        ProteinM5 = c.Single(),
                        FatM5 = c.Single(),
                        CarbohydrateM5 = c.Single(),
                        M6ID = c.Int(),
                        M6NameEng = c.String(),
                        M6NameAr = c.String(),
                        M6Calories = c.Single(),
                        MealTime6 = c.Single(),
                        Expr5 = c.Single(),
                        WeighM6 = c.Single(),
                        ProteinM6 = c.Single(),
                        FatM6 = c.Single(),
                        CarbohydrateM6 = c.Single(),
                        M7ID = c.Int(),
                        M7NameEng = c.String(),
                        M7NameAr = c.String(),
                        M7Calories = c.Single(),
                        MealTime7 = c.Single(),
                        Expr6 = c.Single(),
                        WeighM7 = c.Single(),
                        ProteinM7 = c.Single(),
                        FatM7 = c.Single(),
                        CarbohydrateM7 = c.Single(),
                        M8ID = c.Int(),
                        M8NameEng = c.String(),
                        M8NameAr = c.String(),
                        M8Calories = c.Single(),
                        MealTime8 = c.Single(),
                        Expr7 = c.Single(),
                        WeighM8 = c.Single(),
                        ProteinM8 = c.Single(),
                        FatM8 = c.Single(),
                        CarbohydrateM8 = c.Single(),
                        M9ID = c.Int(),
                        M9NameEng = c.String(),
                        M9NameAr = c.String(),
                        M9Calories = c.Single(),
                        MealTime9 = c.Single(),
                        Expr8 = c.Single(),
                        WeighM9 = c.Single(),
                        ProteinM9 = c.Single(),
                        FatM9 = c.Single(),
                        CarbohydrateM9 = c.Single(),
                        M10ID = c.Int(),
                        M10NameEng = c.String(),
                        M10NameAr = c.String(),
                        M10Calories = c.Single(),
                        MealTime10 = c.Single(),
                        Expr9 = c.Single(),
                        WeighM10 = c.Single(),
                        ProteinM10 = c.Single(),
                        FatM10 = c.Single(),
                        CarbohydrateM10 = c.Single(),
                    })
                .PrimaryKey(t => t.LM_ID);
            
        }
        
        public override void Down()
        {
            DropTable("GL.MenuByDateWebNutrition");
        }
    }
}
